# Generated by Django 2.2.5 on 2020-02-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
