# Generated by Django 2.2.5 on 2020-02-01 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_App', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
