# Generated by Django 2.2.5 on 2020-02-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_App', '0003_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
    ]
