# Generated by Django 2.2.5 on 2020-02-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_App', '0004_question_no_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
